# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rizlone/Desktop/cmake-3.19.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/rizlone/Desktop/cmake-3.19.1-Linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rizlone/Desktop/PROJECT_SOURCE_DIR2/include

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rizlone/Desktop/PROJECT_SOURCE_DIR2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rizlone/Desktop/cmake-3.19.1-Linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/rizlone/Desktop/cmake-3.19.1-Linux-x86_64/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rizlone/Desktop/PROJECT_SOURCE_DIR2/CMakeFiles /home/rizlone/Desktop/PROJECT_SOURCE_DIR2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rizlone/Desktop/PROJECT_SOURCE_DIR2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gvar

# Build rule for target.
gvar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gvar
.PHONY : gvar

# fast build rule for target.
gvar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/build
.PHONY : gvar/fast

amxplugin.o: amxplugin.cpp.o

.PHONY : amxplugin.o

# target to build an object file
amxplugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/amxplugin.cpp.o
.PHONY : amxplugin.cpp.o

amxplugin.i: amxplugin.cpp.i

.PHONY : amxplugin.i

# target to preprocess a source file
amxplugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/amxplugin.cpp.i
.PHONY : amxplugin.cpp.i

amxplugin.s: amxplugin.cpp.s

.PHONY : amxplugin.s

# target to generate assembly for a file
amxplugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/amxplugin.cpp.s
.PHONY : amxplugin.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/main.cpp.s
.PHONY : main.cpp.s

sampgdk.o: sampgdk.c.o

.PHONY : sampgdk.o

# target to build an object file
sampgdk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/sampgdk.c.o
.PHONY : sampgdk.c.o

sampgdk.i: sampgdk.c.i

.PHONY : sampgdk.i

# target to preprocess a source file
sampgdk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/sampgdk.c.i
.PHONY : sampgdk.c.i

sampgdk.s: sampgdk.c.s

.PHONY : sampgdk.s

# target to generate assembly for a file
sampgdk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gvar.dir/build.make CMakeFiles/gvar.dir/sampgdk.c.s
.PHONY : sampgdk.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gvar"
	@echo "... amxplugin.o"
	@echo "... amxplugin.i"
	@echo "... amxplugin.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sampgdk.o"
	@echo "... sampgdk.i"
	@echo "... sampgdk.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

